# Generated by Django 3.1 on 2020-08-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'managed': False},
        ),
    ]
