# Generated by Django 3.1 on 2020-08-17 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200816_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webtext',
            old_name='text',
            new_name='text_cn',
        ),
        migrations.AddField(
            model_name='webtext',
            name='text_mx',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='webtext',
            name='text_us',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='WebSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.websection')),
            ],
        ),
        migrations.CreateModel(
            name='WebImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_us', models.CharField(default='', max_length=100)),
                ('alt_cn', models.CharField(default='', max_length=100)),
                ('alt_mx', models.CharField(default='', max_length=100)),
                ('path_to_file', models.CharField(default='', max_length=100)),
                ('parent_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.websection')),
            ],
        ),
        migrations.AddField(
            model_name='webtext',
            name='parent_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.websection'),
        ),
    ]
