# Generated by Django 3.1 on 2020-08-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200817_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='webimg',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='websection',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='webtext',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
