# Generated by Django 3.1 on 2020-08-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200816_1713'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tutor',
            table='standard_tutor',
        ),
    ]
