# Generated by Django 3.1 on 2020-08-17 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200817_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='webimg',
            name='parent_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.webpage'),
        ),
        migrations.AddField(
            model_name='websection',
            name='parent_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.webpage'),
        ),
        migrations.AddField(
            model_name='webtext',
            name='parent_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.webpage'),
        ),
    ]
