# Generated by Django 3.1 on 2020-08-31 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200817_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='websection',
            name='parent_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.websection'),
        ),
        migrations.CreateModel(
            name='WebInnerLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.webpage')),
                ('parent_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.websection')),
            ],
        ),
    ]
