# Generated by Django 3.1 on 2020-08-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('us_grade', models.IntegerField(default=0)),
                ('placement_code', models.CharField(default='', max_length=1000)),
                ('contact_email', models.EmailField(default='', max_length=254)),
                ('gclass_email', models.EmailField(default='', max_length=254)),
                ('slack_email', models.EmailField(default='', max_length=254)),
                ('courses_enrolled', models.CharField(default='', max_length=1000)),
                ('behavioral_comment', models.TextField(default='')),
                ('misc_comment', models.TextField(default='')),
                ('attendance_record', models.TextField(default='')),
                ('academic_record', models.TextField(default='')),
                ('behavioral_record', models.TextField(default='')),
                ('admin_extra', models.TextField(default='')),
            ],
        ),
    ]
