# Generated by Django 3.1 on 2020-08-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_comment',
            field=models.TextField(default=''),
        ),
    ]
