# Generated by Django 3.1 on 2020-08-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0002_student_academic_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='us_grade',
            field=models.IntegerField(default=1),
        ),
    ]
