# Generated by Django 3.1 on 2020-08-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0003_auto_20200811_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=100)),
                ('abbrev_name', models.CharField(default='', max_length=100)),
                ('division', models.CharField(default='', max_length=100)),
                ('subdivision', models.CharField(default='', max_length=100)),
                ('level', models.IntegerField(default=0)),
                ('tutors_teaching', models.TextField(default='')),
                ('students_enrolled', models.TextField(default='')),
                ('subject_leader_id', models.CharField(default='', max_length=100)),
                ('primary_contact', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('tutor_id', models.CharField(default='', max_length=100)),
                ('students_attended', models.TextField(default='')),
                ('session_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('contact_email', models.EmailField(default='', max_length=254)),
                ('age', models.IntegerField(default=1)),
                ('us_grade', models.IntegerField(default=1)),
                ('slack_email', models.EmailField(default='', max_length=254)),
                ('gclass_email', models.EmailField(default='', max_length=254)),
                ('course_assignment_code', models.CharField(default='', max_length=1000)),
                ('attendance_record', models.TextField(default='')),
                ('admin_extra', models.TextField(default='')),
                ('random_id', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='random_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
