# Generated by Django 3.1 on 2020-08-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0004_auto_20200811_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_name',
            new_name='parent_course',
        ),
        migrations.AddField(
            model_name='session',
            name='conducted',
            field=models.BooleanField(default=False),
        ),
    ]
