# Generated by Django 3.1 on 2020-08-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0005_auto_20200812_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='us_grade',
        ),
        migrations.AddField(
            model_name='student',
            name='grade_level',
            field=models.IntegerField(default=1),
        ),
    ]
