# Generated by Django 3.1 on 2020-08-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0006_auto_20200812_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade_level',
        ),
    ]
