# Generated by Django 3.1 on 2020-08-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0007_remove_student_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(default=1),
        ),
    ]
