# Generated by Django 3.1 on 2020-08-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0008_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
