# Generated by Django 3.1 on 2020-08-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0009_session_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='cs_hours_sem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='prep_hours',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tutor',
            name='teaching_hours',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutoring_history',
            field=models.TextField(default=''),
        ),
    ]
