# Generated by Django 3.1 on 2020-08-31 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0010_auto_20200813_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=100)),
                ('abbrev_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='random_id',
            new_name='gclass_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='division',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subdivision',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject_leader_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='slack_email',
        ),
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='SuperCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=100)),
                ('abbrev_name', models.CharField(default='', max_length=100)),
                ('parent_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='standard.packagecourse')),
                ('subject_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standard.tutor')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='parent_super',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='standard.supercourse'),
        ),
    ]
