# Generated by Django 3.1 on 2020-08-31 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0011_auto_20200831_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=100)),
                ('abbrev_name', models.CharField(default='', max_length=100)),
                ('level', models.IntegerField(default=0)),
                ('tutors_teaching', models.TextField(default='')),
                ('students_enrolled', models.TextField(default='')),
                ('primary_contact', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PackageInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField(default=1)),
                ('parent_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='standard.packagecourse')),
            ],
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='cs_hours_sem',
            new_name='hours_sem_total',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='parent_super',
        ),
        migrations.RemoveField(
            model_name='course',
            name='primary_contact',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students_enrolled',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tutors_teaching',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='course_assignment_code',
        ),
        migrations.AddField(
            model_name='course',
            name='parent_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='standard.packagecourse'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='standard.tutor'),
        ),
        migrations.DeleteModel(
            name='SuperCourse',
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='parent_course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='standard.course'),
        ),
    ]
