# Generated by Django 3.1 on 2020-08-31 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0012_auto_20200831_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinstance',
            name='abbrev_name',
        ),
        migrations.RemoveField(
            model_name='courseinstance',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='session',
            name='parent_course',
        ),
        migrations.RemoveField(
            model_name='session',
            name='tutor_id',
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='section',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='parent_course_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='standard.courseinstance'),
        ),
        migrations.AddField(
            model_name='session',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='standard.tutor'),
        ),
    ]
