# Generated by Django 3.1 on 2020-08-31 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0014_auto_20200831_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinstance',
            name='tutor',
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='tutors',
            field=models.ManyToManyField(null=True, to='standard.Tutor'),
        ),
        migrations.AddField(
            model_name='session',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='standard.tutor'),
        ),
    ]
