# Generated by Django 3.1 on 2020-09-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0017_auto_20200831_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='tutor',
        ),
        migrations.AddField(
            model_name='session',
            name='class_report_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='session',
            name='monitors',
            field=models.ManyToManyField(related_name='sessions_monitoring', to='standard.Tutor'),
        ),
        migrations.AddField(
            model_name='session',
            name='students_attending',
            field=models.ManyToManyField(related_name='sessions_attending', to='standard.Student'),
        ),
        migrations.AddField(
            model_name='session',
            name='tutors',
            field=models.ManyToManyField(related_name='sessions_tutoring', to='standard.Tutor'),
        ),
        migrations.RemoveField(
            model_name='session',
            name='students_attended',
        ),
        migrations.AddField(
            model_name='session',
            name='students_attended',
            field=models.ManyToManyField(related_name='sessions_attended', to='standard.Student'),
        ),
    ]
