# Generated by Django 3.1 on 2020-09-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0020_auto_20200902_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstance',
            name='students_enrolled',
            field=models.ManyToManyField(blank=True, to='standard.Student'),
        ),
        migrations.AlterField(
            model_name='session',
            name='monitors',
            field=models.ManyToManyField(blank=True, related_name='sessions_monitoring', to='standard.Tutor'),
        ),
    ]
